version: '3'
services:
  db:
    image: postgres:14
    container_name: projectPyqt6
    restart: always
    environment:
      POSTGRES_USER: pyqt
      POSTGRES_PASSWORD: pyqt6
      POSTGRES_DB: project
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
